### ISSUE TITLE
Downloading Powerpoint files fails

### ISSUE THREAD

**Issue by haesleinhuepf** [bioimage-io/Workshop-June2024-Madrid#6]
Hi all,

first of all thanks so much for making these training materials openly available! That's fantastic. I just tried to download the PPTX files in [this folder](https://github.com/bioimage-io/Workshop-June2024-Madrid/tree/main/Workshop) using github Desktop and I receive this error:

```
Cloning into 'C:\structure\code\Workshop-June2024-Madrid'...
remote: Enumerating objects: 166, done.        
remote: Counting objects: 100% (166/166), done.        
remote: Compressing objects: 100% (144/144), done.        
remote: Total 166 (delta 87), reused 35 (delta 11), pack-reused 0        
Receiving objects: 100% (166/166), 18.29 MiB | 1.13 MiB/s, done.
Resolving deltas: 100% (87/87), done.
Downloading Workshop/20240610 - Deep Learning for Microscopy - Ignacio Arganda.pptx (149 MB)
Error downloading object: Workshop/20240610 - Deep Learning for Microscopy - Ignacio Arganda.pptx (5cb42b4): Smudge error: Error downloading Workshop/20240610 - Deep Learning for Microscopy - Ignacio Arganda.pptx (5cb42b42935560603944e1047eba5e36685e51288061c770c5db37a2ef20e349): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to 'C:\structure\code\Workshop-June2024-Madrid\.git\lfs\logs\20240611T165604.5336956.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Workshop/20240610 - Deep Learning for Microscopy - Ignacio Arganda.pptx: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Also downloading the files using the browser doesn't work. The file downloaded [here](https://github.com/bioimage-io/Workshop-June2024-Madrid/blob/main/Workshop/20240610%20-%20Deep%20Learning%20for%20Microscopy%20-%20Ignacio%20Arganda.pptx) does not open in PowerPoint.

Would it maybe be possible to upload the PPTx files (and or other big data files) to https://zenodo.org or https://f1000research.com/neubias or https://figshare.com instead of to a github repository? That would certainly skyrocket reusability (the R in FAIR) of the training materials.

Read more:
https://focalplane.biologists.com/2023/07/26/sharing-your-poster-on-figshare/
https://focalplane.biologists.com/2023/02/15/sharing-research-data-with-zenodo/
https://f1000research.com/articles/9-613

Big thanks!

Best,
Robert

**Comment by cfusterbarcelo** [comment]
Hi Robert!

Thank you so much for your feedback and for pointing out the issues with downloading the training materials. We were facing some memory issues with GitHub. We have decided to upload all materials to zenodo. You can access it [here](https://zenodo.org/records/11657763).

We hope this solution works and enhances the reusability of the training materials.

Best,
Caterina
